### ISSUE TITLE
增加客户类型

### ISSUE THREAD

**Issue by lijiarui** [juzibot/mingdao-workflow#1]
## 内容包括：
- 客户名称
- SKU （Wechaty、句子秒回、句客宝）
- 客户类型（大客户、小客户、代理商。。。）

![image](https://user-images.githubusercontent.com/6419514/145716878-6354125f-31e4-4241-a254-2b25f507e428.png)

**Comment by bung87** [comment]
close in https://github.com/juzibot/mingdao-workflow/commit/1dd592abc778b6925c56fdedaafedac34d2c740d
