### ISSUE TITLE
核桃编程21年2月份应该有数据，现在没有

### ISSUE THREAD

**Issue by socialok** [juzibot/mingdao-workflow#4]
![image](https://user-images.githubusercontent.com/90542573/145720121-f6d03bc8-bbf6-4b73-9c2e-1392d54b4f00.png)
![image](https://user-images.githubusercontent.com/90542573/145720326-4990f0bb-1846-4172-9923-2b3fddcf436b.png)

**Comment by socialok** [comment]
CRM系统里面核桃编程是有2月份的数据的，但是转换后的表格里面没有了2月份的数据

**Comment by bung87** [comment]
合同表里只有这三行是核桃编程的
日期 数量
2020-11-27  3
2020-11-28 3 
2020-08-28 3
