### ISSUE TITLE
客户维度 MRR， 缺少内容

### ISSUE THREAD

**Issue by lijiarui** [juzibot/mingdao-workflow#6]
![image](https://user-images.githubusercontent.com/6419514/145721233-a0b78cd8-705e-4f8d-86ca-f7d4c495c786.png)

## 1. 增加列
- [ ] SKU
- [ ] 客户类型
- [ ] 行业

## 2. 表头
- [ ] 表头

**Comment by bung87** [comment]
close in c7a058a
